package com.bestbuy.bbym.ise.drp.recsheet;

public enum EssentialTypeEnum {
    HANDSFREE(1), MEMORY(2), CASE_SHIELD(3), APPCESSORIES(4), CHARGER(5), GEEK_SQUAD_PROTECTION(6), TRADE_IN_PLUS(7),
    FINANCING(8), INTERNET(9), EMAIL(10), MUSIC(11), VIDEO(12), PHOTOS(13), TV(14), NAVIGATION(15), GAMING(16),
    TEXTING(17), UNLOCKED(18), OTHER(19), DATA_TRANSFER(20), SOCIAL_NETWORKING(21), PERSONAL_EMAIL_SETUP(22),
    POWER_MANAGEMENT(23), BLUETOOTH_PAIRING(24), VOICEMAIL_SETUP(25), APPLICATIONS(26), OTHER_WOW(27),
    SOFTWARE_UPDATES(28), PERFECT_DEVICE_FOR_YOU(29), SEEN_THAT_YOU_LIKE(30), WHY_NEW_COMPUTER_OR_TABLET(31),
    WHERE_USE_COMP_OR_TAB(32), PROGRAMS_USED_MOST(33), PROCESSING_SPEED(34), GRAPHICS(35), SCREEN_SIZE(36),
    BATTERY_LIFE(37), PRICE(38), POWER(39), STYLE(40), COLOR(41), OTHER_THE_RIGHT_DEVICE(42), HIGH_SPEED_INTERNET(43),
    WIRELESS(44), MOBILE_BROADBAND(45), COMMENTS(46), DEVICES_TO_CONNECT_WITH(47), EXISTING_HARDWARE(48),
    RECOMMENDATIONS(49), HEARD_OF_GEEK_SQUAD(50), HEARD_OF_GEEK_SQUAD_PROTECTION(51), GS_TECH_SERVICES(52),
    INTERNET_SECURITY(53), MICROSOFT_OFFICE_APP_CARD(54), PRINTER_OFFICE_SUPPLIES(55), ACCESSORIES(56), NETWORKING(57),
    EXTERNAL_STORAGE(58), FINANCING_AND_REWARDS(59), HEADPHONES_SPEAKERS(60);

    private int id;

    private EssentialTypeEnum(int id) {
	this.id = id;
    }

    public Long getId() {
	return new Long(id);

    }
}
