SET MODE Oracle;

Insert into BST_ISE_SCH01.REC_SHT_SUMM (PLAN_INFO,DEVICE_INFO,GSP_PLAN_INFO,BUYBACK_PLAN_INFO,CREATED_BY,CREATED_ON,AMENDED_BY,AMENDED_ON) 
values ('Plan Info','Device Info','GSP Plan Info','BuyBack Info','a175157', SYSDATE, 'a175157', SYSDATE);


Insert into BST_ISE_SCH01.REC_SHT_SUMM (PLAN_INFO,DEVICE_INFO,GSP_PLAN_INFO,BUYBACK_PLAN_INFO,CREATED_BY,CREATED_ON,AMENDED_BY,AMENDED_ON) 
values ('Plan','Device','GSP Plan Info','BuyBack Info','a175157',SYSDATE,'a175157', SYSDATE);


Insert into BST_ISE_SCH01.REC_SHT_SUMM (PLAN_INFO,DEVICE_INFO,GSP_PLAN_INFO,BUYBACK_PLAN_INFO,CREATED_BY,CREATED_ON,AMENDED_BY,AMENDED_ON) 
values ('Bills Plan','Bills Device','GSP Plan Info','BuyBack Info','a175157',SYSDATE,'a915714',SYSDATE);


Insert into BST_ISE_SCH01.REC_SHT_SUMM (PLAN_INFO,DEVICE_INFO,GSP_PLAN_INFO,BUYBACK_PLAN_INFO,CREATED_BY,CREATED_ON,AMENDED_BY,AMENDED_ON) 
values ('Udayas Plan','Udayas Device','GSP Plan Info','BuyBack Info','a915714',SYSDATE,'a909241',SYSDATE);
