SET MODE Oracle;

INSERT INTO BST_ISE_SCH01.recommendation_essential_type
(recommendation_esential_typ_id, description, created_by, created_on)
values(seq_recommendation_esentl_type.NEXTVAL,'E-mail', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Music', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Video', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Photo', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'TV', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Navigation', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Gaming', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Texting', 'a911002', SYSDATE),
(seq_recommendation_esentl_type.NEXTVAL,'Unlocked', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC WOW Power on computer', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC WOW Install internet security software', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC WOW Set up email', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC WOW Schedule operating system updates', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security 6 months', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security Webroot', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security Kaspersky', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Internet security Titanium', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS tech support', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS support 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS support 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS support 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS protection', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS Laptop protection 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS Laptop protection 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS Laptop protection 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS Desktop protection 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS Desktop protection 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC GS Desktop protection 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Databack up or transfer', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Microsoft office', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Restore media', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'PC Personalized setup and restore media', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC WOW Power on computer', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC WOW Install internet security software', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC WOW Set up email', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC WOW Schedule operating system updates', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security 6 months', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security Webroot', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security Kaspersky', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Internet security Titanium', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS tech support', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS support 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS support 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS support 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS protection', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS Laptop protection 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS Laptop protection 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS Laptop protection 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS Desktop protection 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS Desktop protection 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC GS Desktop protection 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Databack up or transfer', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Microsoft office for MAC', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Apple TV', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'MAC Parallels desktop 7 for MAC', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET WOW Power on computer', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET WOW Set up social networking account and install 3 apps', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET WOW Set up email and include email app or web browser', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET WOW Schedule operating system updates', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS tech support', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS support 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS support 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS support 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS protection and Locked&Found protection', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS protection 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS protection 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS protection 3 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET Locked&Found protection 1 year', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET Locked&Found protection 2 years', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET Shield install', 'a911002', SYSDATE)
(seq_recommendation_esentl_type.NEXTVAL,'TABLET GS New network setup', 'a911002', SYSDATE);