SET MODE Oracle;

INSERT INTO BST_ISE_SCH01.RECOMMENDATION(
	RECOMMENDATION_ID,
	DEVICE_CAPABILITIES,
	WOW_REQUIREMENTS,
	RECOMMENDED_SUBSCRIPTION,
	RECOMMENDED_DEVICE,
	NET_USE_INFO,
	NOTES,
	CREATED_BY,
	CREATED_ON,
	AMENDED_BY,
	AMENDED_ON,
	STORE_ID,
	EMP_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MOBILE_NO,
	BEST_CONTACT_TM_INFO,
	BBY_CUSTOMER_ID,
	UPGRADE_REMINDER_TEXT,
	UPGRADE_REMINDER_CALL,
	UPGRADE_ELIGIBILITY_DATE,
	SUBSCRIPTION_INFO,
	TRADE_IN_VAL,
	EMP_CRT_FRST_NM,
	EMP_CRT_LAST_NM,
	EMP_ALT_FRST_NM,
	EMP_ALT_LAST_NM,
	REC_SHT_TYP,
	ADDR,
    CITY,
    STATE,
    ZIPCODE,
    BBY_CNS_FRST_NM,
    BBY_CNS_LAST_NM,
    BBY_CNS_PH_NBR,
    BBY_CNS_PH_EXT,
    LANG)
values(
	1,
	0,
	0,
	'someRecommendedSubscription',
	'someRecommendedDevice',
	'someNetUseInfo',
	'someNotes',
	'a123',
	SYSDATE,
	null,
	null,
	'0644',
	'someSpecialistContactInfo',
	'someFirstName',
	'someLastName',
	'5551111111',
	'someBestTimeToContact',
	'someBbyCustomerId',
	null,
	1,
	null,
	'someSubscriptionInfo',
	111.23,
	'someEmpCreateFirstName',
	'someEmpCreateLastName',
	null,
	null,
	1,
	'someAddress',
	'someCity',
	'someState',
	'55435',
	'someBbyConsultantFirstName',
	'someBbyConsultantLastName',
	'6126126122',
	'1234',
	'en_US');


INSERT INTO BST_ISE_SCH01.RECOMMENDATION(
	RECOMMENDATION_ID,
	DEVICE_CAPABILITIES,
	WOW_REQUIREMENTS,
	RECOMMENDED_SUBSCRIPTION,
	RECOMMENDED_DEVICE,
	NET_USE_INFO,
	NOTES,
	CREATED_BY,
	CREATED_ON,
	AMENDED_BY,
	AMENDED_ON,
	STORE_ID,
	EMP_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MOBILE_NO,
	BEST_CONTACT_TM_INFO,
	BBY_CUSTOMER_ID,
	UPGRADE_REMINDER_TEXT,
	UPGRADE_REMINDER_CALL,
	UPGRADE_ELIGIBILITY_DATE,
	SUBSCRIPTION_INFO,
	TRADE_IN_VAL,
	EMP_CRT_FRST_NM,
	EMP_CRT_LAST_NM,
	EMP_ALT_FRST_NM,
	EMP_ALT_LAST_NM,
	REC_SHT_TYP,
	LANG)
values(
	2,
	0,
	0,
	null,
	null,
	null,
	null,
	'a234',
	SYSDATE,
	null,
	null,
	'0655',
	null,
	null,
	'someOtherLastName',
	'5552222222',
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	1,
	'en_US');

INSERT INTO BST_ISE_SCH01.recommendation_essential_type
   (RECOMMENDATION_ESENTIAL_TYP_ID,
    DESCRIPTION,
    CREATED_BY,
    CREATED_ON,
    AMENDED_BY,
    AMENDED_ON)
values(
    1,
    'ACCESSORIES',
    'a123',
    SYSDATE,
    null,
    null);

INSERT INTO BST_ISE_SCH01.recommendation_essential_type
   (RECOMMENDATION_ESENTIAL_TYP_ID,
    DESCRIPTION,
    CREATED_BY,
    CREATED_ON,
    AMENDED_BY,
    AMENDED_ON)
values(
    2,
    'MEMORY',
    'a234',
    SYSDATE,
    null,
    null);

INSERT INTO BST_ISE_SCH01.recommendation_essential
   (RECOMMENDATION_ESSENTIAL_ID,
    RECOMMENDATION_ID,
    RECOMMENDATION_ESENTIAL_TYP_ID,
    COMMENTS,
    CREATED_BY,
    CREATED_ON,
    AMENDED_BY,
    AMENDED_ON)
VALUES ( 
    1, 
    1, 
    1,
    'someComment', 
    'a234',
    SYSDATE,
    null,
    null);

INSERT INTO BST_ISE_SCH01.recommendation_essential
   (RECOMMENDATION_ESSENTIAL_ID,
    RECOMMENDATION_ID,
    RECOMMENDATION_ESENTIAL_TYP_ID,
    COMMENTS,
    CREATED_BY,
    CREATED_ON,
    AMENDED_BY,
    AMENDED_ON)
VALUES ( 
    2, 
    2, 
    2,
   'someOtherComment', 
    'a234',
    SYSDATE,
    null,
    null);


-- new inserts to test amended_on date range
-- for date fields like amended_on
-- to_date('12-MAR-12','DD-MON-RR')

INSERT INTO BST_ISE_SCH01.RECOMMENDATION(RECOMMENDATION_ID, CREATED_BY,CREATED_ON, first_name, last_name, amended_by, amended_on, REC_SHT_TYP)
values(
4,
'a1234',
SYSDATE,
'Bill', 'McGough', 'a915714', SYSDATE, 1);


INSERT INTO BST_ISE_SCH01.RECOMMENDATION(RECOMMENDATION_ID, CREATED_BY, CREATED_ON, first_name, last_name, amended_by, amended_on, REC_SHT_TYP)
values(
5,
'a5234',
SYSDATE,
'Udaya', 'Duvvuri', 'a909241', SYSDATE, 1);





------- some more test data ------------
INSERT INTO BST_ISE_SCH01.RECOMMENDATION(RECOMMENDATION_ID, CREATED_BY,CREATED_ON, first_name, last_name, amended_by, amended_on, REC_SHT_TYP)
values(
8,
'a81234',
SYSDATE,
'Sam', 'Sneed', 'a915814', SYSDATE, 1);


INSERT INTO BST_ISE_SCH01.RECOMMENDATION(RECOMMENDATION_ID, CREATED_BY, CREATED_ON, first_name, last_name, amended_by, amended_on, REC_SHT_TYP)
values(
9,
'a95234',
SYSDATE,
'Ben', 'Hogan', 'a809241', SYSDATE, 1);



------- testing for the computers and tablets ------------

INSERT INTO BST_ISE_SCH01.RECOMMENDATION(
	RECOMMENDATION_ID,
	DEVICE_CAPABILITIES,
	WOW_REQUIREMENTS,
	RECOMMENDED_SUBSCRIPTION,
	RECOMMENDED_DEVICE,
	NET_USE_INFO,
	NOTES,
	CREATED_BY,
	CREATED_ON,
	AMENDED_BY,
	AMENDED_ON,
	STORE_ID,
	EMP_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MOBILE_NO,
	BEST_CONTACT_TM_INFO,
	BBY_CUSTOMER_ID,
	UPGRADE_REMINDER_TEXT,
	UPGRADE_REMINDER_CALL,
	UPGRADE_ELIGIBILITY_DATE,
	SUBSCRIPTION_INFO,
	TRADE_IN_VAL,
	EMP_CRT_FRST_NM,
	EMP_CRT_LAST_NM,
	EMP_ALT_FRST_NM,
	EMP_ALT_LAST_NM,
	REC_SHT_TYP,
	ADDR,
    CITY,
    STATE,
    ZIPCODE,
    BBY_CNS_FRST_NM,
    BBY_CNS_LAST_NM,
    BBY_CNS_PH_NBR,
    BBY_CNS_PH_EXT)
values(
	21,
	0,
	0,
	'someRecommendedSubscription',
	'someRecommendedDevice',
	'someNetUseInfo',
	'someNotes',
	'a123',
	SYSDATE,
	null,
	null,
	'0645',
	'someSpecialistContactInfo',
	'someFirstName',
	'someLastName',
	'5551111111',
	'someBestTimeToContact',
	'someBbyCustomerId',
	null,
	1,
	null,
	'someSubscriptionInfo',
	111.23,
	'someEmpCreateFirstName',
	'someEmpCreateLastName',
	null,
	null,
	3,
	'someAddress',
	'someCity',
	'someState',
	'55435',
	'someBbyConsultantFirstName',
	'someBbyConsultantLastName',
	'6126126122',
	'1234');


INSERT INTO BST_ISE_SCH01.RECOMMENDATION(
	RECOMMENDATION_ID,
	DEVICE_CAPABILITIES,
	WOW_REQUIREMENTS,
	RECOMMENDED_SUBSCRIPTION,
	RECOMMENDED_DEVICE,
	NET_USE_INFO,
	NOTES,
	CREATED_BY,
	CREATED_ON,
	AMENDED_BY,
	AMENDED_ON,
	STORE_ID,
	EMP_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MOBILE_NO,
	BEST_CONTACT_TM_INFO,
	BBY_CUSTOMER_ID,
	UPGRADE_REMINDER_TEXT,
	UPGRADE_REMINDER_CALL,
	UPGRADE_ELIGIBILITY_DATE,
	SUBSCRIPTION_INFO,
	TRADE_IN_VAL,
	EMP_CRT_FRST_NM,
	EMP_CRT_LAST_NM,
	EMP_ALT_FRST_NM,
	EMP_ALT_LAST_NM,
	REC_SHT_TYP)
values(
	22,
	0,
	0,
	null,
	null,
	null,
	null,
	'a234',
	SYSDATE,
	null,
	null,
	'0655',
	null,
	null,
	'someOtherLastName',
	'5552222222',
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	3);
