DELETE FROM BST_ISE_SCH01.TRIAGE_RCMD_ACTN;
DELETE FROM BST_ISE_SCH01.TRIAGE_RCMD_SKU;
DELETE FROM BST_ISE_SCH01.SKU;
DELETE FROM BST_ISE_SCH01.TRIAGE_HIST;
DELETE FROM BST_ISE_SCH01.TRIAGE_RCMD;
DELETE FROM BST_ISE_SCH01.TRIAGE_ACTN;
DELETE FROM BST_ISE_SCH01.TRIAGE_RSLN_LKP;
DELETE FROM BST_ISE_SCH01.TRIAGE_ISSU_LKP;
