DELETE FROM BST_ISE_SCH01.WORKFLOW_ATTRIBUTE_HIST;

DELETE FROM BST_ISE_SCH01.RECOMMENDATION_ESSENTIAL;

DELETE FROM BST_ISE_SCH01.RECOMMENDATION_ESSENTIAL_TYPE;

DELETE FROM BST_ISE_SCH01.RECOMMENDATION;

DELETE FROM BST_ISE_SCH01.ISE_PROPERTIES;

DELETE FROM BST_ISE_SCH01.HOTLINKS;

DELETE FROM BST_ISE_SCH01.DIALOG_QUESTION_ANSWER_HIST;

DELETE FROM BST_ISE_SCH01.DIALOG_QUESTION_HIST;

DELETE FROM BST_ISE_SCH01.DIALOG_QUESTION_ANSWER;

DELETE FROM BST_ISE_SCH01.DIALOG_QUESTION;

DELETE FROM BST_ISE_SCH01.DIALOG_HISTORY;

DELETE FROM BST_ISE_SCH01.WORKFLOW_STEP_HIST;

DELETE FROM BST_ISE_SCH01.WORKFLOW;

DELETE FROM BST_ISE_SCH01.HOTLINKS;


