SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS BST_ISE_SCH01;

CREATE TABLE BST_ISE_SCH01.TRIAGE_ACTN 
    ( 
     ACTN_ID NUMBER (10)  NOT NULL , 
     ACTN VARCHAR2 (250 )  NOT NULL , 
     ACT_FLG NUMBER(1,0)  NOT NULL ,
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE
    );

ALTER TABLE BST_ISE_SCH01.TRIAGE_ACTN 
    ADD CONSTRAINT TRIAGE_ACTN_PK PRIMARY KEY ( ACTN_ID ) ;

CREATE TABLE BST_ISE_SCH01.TRIAGE_ISSU_LKP
    ( 
     ISSU_ID NUMBER (10)  NOT NULL , 
     ISSU_DESC VARCHAR2 (250 )  NOT NULL , 
     TOOLTIP VARCHAR2 (2000 ) , 
     DISPL_ORD NUMBER (10)  NOT NULL , 
     ACT_FLG NUMBER(1,0)  NOT NULL , 
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE
    );

ALTER TABLE BST_ISE_SCH01.TRIAGE_ISSU_LKP 
    ADD CONSTRAINT TRIAGE_ISSU_LKP_PK PRIMARY KEY ( ISSU_ID ) ;



CREATE TABLE BST_ISE_SCH01.TRIAGE_RCMD
    ( 
     RCMD_ID NUMBER (10)  NOT NULL , 
     RCMD VARCHAR2 (1000 )  NOT NULL , 
     ISSU_ID NUMBER (10)  NOT NULL,
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE
    );

ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD
    ADD CONSTRAINT TRIAGE_RCMD_PK PRIMARY KEY ( RCMD_ID ) ;
    
ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD 
    ADD CONSTRAINT TRIAGE_ISSU_LKP_FK FOREIGN KEY 
    ( 
     ISSU_ID
    ) 
    REFERENCES BST_ISE_SCH01.TRIAGE_ISSU_LKP 
    ( 
     ISSU_ID
    ) 
    NOT DEFERRABLE 
;

CREATE TABLE BST_ISE_SCH01.TRIAGE_RSLN_LKP 
    ( 
     RSNL_ID NUMBER (10)  NOT NULL ,
     RSLN_DESC VARCHAR2 (250 )  NOT NULL , 
     DISPL_ORD NUMBER (10)  NOT NULL , 
     ACT_FLG NUMBER(1,0)  NOT NULL ,
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE
    );

ALTER TABLE BST_ISE_SCH01.TRIAGE_RSLN_LKP 
    ADD CONSTRAINT TRIAGE_RSLN_LKP_PK PRIMARY KEY ( RSNL_ID ) ;



CREATE TABLE BST_ISE_SCH01.TRIAGE_HIST
    ( 
     HIST_ID NUMBER (10)  NOT NULL , 
     DEVICE_SN VARCHAR2 (100)  NOT NULL , 
     ISSU_CMNT VARCHAR2 (2000 ) , 
     RSLN_CMNT VARCHAR2 (2000 ) , 
     PROTECTION_PLAN_ID VARCHAR2 (60 ) , 
     TECH_CHKR_ISSUES VARCHAR2(2000)  NOT NULL , 
     RCMD_ID NUMBER (10)  NOT NULL , 
     RSNL_ID NUMBER(10)  NOT NULL,
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE,
     CUST_BENI VARCHAR2(100)
    ) ;

ALTER TABLE BST_ISE_SCH01.TRIAGE_HIST 
    ADD CONSTRAINT TRIAGE_HIST_PK PRIMARY KEY ( HIST_ID ) ;
 
 
ALTER TABLE BST_ISE_SCH01.TRIAGE_HIST 
    ADD CONSTRAINT TRIAGE_RCMD_FK FOREIGN KEY 
    ( 
     RCMD_ID
    ) 
    REFERENCES BST_ISE_SCH01.TRIAGE_RCMD 
    ( 
     RCMD_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE BST_ISE_SCH01.TRIAGE_HIST 
    ADD CONSTRAINT TRIAGE_RSLN_LKP_FK FOREIGN KEY 
    ( 
     RSNL_ID
    ) 
    REFERENCES BST_ISE_SCH01.TRIAGE_RSLN_LKP 
    ( 
     RSNL_ID
    ) 
    NOT DEFERRABLE 
;

CREATE INDEX BST_ISE_SCH01.TRIAGE_HIST_IDX1 ON BST_ISE_SCH01.TRIAGE_HIST 
    ( 
     DEVICE_SN ASC 
    );



CREATE TABLE BST_ISE_SCH01.TRIAGE_RCMD_ACTN 
    ( 
     RCMD_ACTN_ID NUMBER (10)  NOT NULL , 
     DISPL_ORD NUMBER (10)  NOT NULL , 
     ACTN_ID NUMBER (10)  NOT NULL , 
     RCMD_ID NUMBER (10)  NOT NULL , 
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE
    );


ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD_ACTN 
    ADD CONSTRAINT TRIAGE_RCMD_ACTN_PK PRIMARY KEY ( RCMD_ACTN_ID ) ;

ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD_ACTN 
    ADD CONSTRAINT TRIAGE_ACTN_FK1 FOREIGN KEY 
    ( 
     ACTN_ID
    ) 
    REFERENCES BST_ISE_SCH01.TRIAGE_ACTN 
    ( 
     ACTN_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD_ACTN 
    ADD CONSTRAINT TRIAGE_RCMD_FK2 FOREIGN KEY 
    ( 
     RCMD_ID
    ) 
    REFERENCES BST_ISE_SCH01.TRIAGE_RCMD 
    ( 
     RCMD_ID
    ) 
    NOT DEFERRABLE 
;



CREATE TABLE BST_ISE_SCH01.SKU 
    ( 
    SKU VARCHAR2(50) NOT NULL,
    SKU_NM VARCHAR2(100),
    SKU_DESC VARCHAR2(250),
    TECHNLGY_TYP VARCHAR2(50),
    UPC VARCHAR2(100),
    CARRIER VARCHAR(30),
    MFG_NM VARCHAR(100),
    ACT_FLG NUMBER(1,0),
    OS_NM VARCHAR2(30),
    MDL_NBR VARCHAR2(100),
    ATTR1 VARCHAR2(250),
    ATTR2 VARCHAR2(250),
    ATTR3 VARCHAR2(250),
    ATTR4 VARCHAR2(250),
    ATTR5 VARCHAR2(250),
    ATTR6 VARCHAR2(250),
    ATTR7 VARCHAR2(250),
    ATTR8 VARCHAR2(250),
    ATTR9 VARCHAR2(250),
    ATTR10 VARCHAR2(250),
    CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE DATE  NOT NULL ,
     AMENDED_BY VARCHAR2(20 ),
     AMENDED_ON DATE
    );
ALTER TABLE BST_ISE_SCH01.SKU 
    ADD CONSTRAINT SKU_PK PRIMARY KEY ( SKU ) ;

CREATE TABLE BST_ISE_SCH01.TRIAGE_RCMD_SKU 
    ( 
     RCMD_ID NUMBER (10)  NOT NULL , 
     SKU VARCHAR2(50)  NOT NULL , 
     CREATED_BY VARCHAR2 (20 )  NOT NULL , 
     CREATED_DATE TIMESTAMP  NOT NULL 
    ) ;

ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD_SKU 
    ADD CONSTRAINT TRIAGE_RCMD_SKU_PK PRIMARY KEY ( RCMD_ID, SKU ) ;


ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD_SKU 
    ADD CONSTRAINT TRIAGE_RCMD_FK1 FOREIGN KEY 
    ( 
     RCMD_ID
    ) 
    REFERENCES BST_ISE_SCH01.TRIAGE_RCMD 
    ( 
     RCMD_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE BST_ISE_SCH01.TRIAGE_RCMD_SKU 
    ADD CONSTRAINT SKU_FK FOREIGN KEY 
    ( 
     SKU
    ) 
    REFERENCES BST_ISE_SCH01.SKU 
    ( 
     SKU
    ) 
    NOT DEFERRABLE 
;

CREATE SEQUENCE BST_ISE_SCH01.TRIAGE_ACTN_SEQ 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE BST_ISE_SCH01.TRIAGE_HIST_SEQ 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE BST_ISE_SCH01.TRIAGE_ISSU_LKP_SEQ 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE BST_ISE_SCH01.TRIAGE_RCMD_SEQ 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE BST_ISE_SCH01.TRIAGE_RCMD_ACTN_SEQ 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE BST_ISE_SCH01.TRIAGE_RSLN_LKP_SEQ 
    START WITH 1 
    INCREMENT BY 1 
;
