SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS BST_ISE_SCH01;

CREATE TABLE BST_ISE_SCH01.TRD_IN_DEVC_LIST
(
   ID VARCHAR2(100) NOT NULL,
   DTA_SHARING_KEY      VARCHAR2 (100 ) NOT NULL,
   HANDSET_ID    VARCHAR2 (50 ),
   PH_NBR    VARCHAR2 (30),
   DEVC_DESC         VARCHAR2 (100 ),
   CARR 		VARCHAR2(20),
   HANDSET_ID_TYPE 	VARCHAR2(20),
   SRC 	VARCHAR2(20),
   SEL_FLAG 	NUMBER(1,0),
   CREATED_BY   VARCHAR2 (20 ) NOT NULL,
   CREATED_ON   DATE NOT NULL,
   AMENDED_BY   VARCHAR2 (20 ),
   AMENDED_ON   DATE
);



ALTER TABLE BST_ISE_SCH01.TRD_IN_DEVC_LIST
  ADD CONSTRAINT TRD_IN_DEVC_LIST_PK
  PRIMARY KEY (ID);