SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS BST_ISE_SCH01;

CREATE TABLE BST_ISE_SCH01.CONFIG 
    ( 
     CONFIG_ID   NUMBER(10) NOT NULL ,
    CONFIG_TYP  VARCHAR2(100) NOT NULL ,
    PARAM_NAME  VARCHAR2(200) NOT NULL ,
    DESCRIPTION VARCHAR2(400) ,
    CREATED_BY  VARCHAR2(40) NOT NULL ,
    CREATED_ON DATE NOT NULL ,
    AMENDED_BY VARCHAR2(40) ,
    AMENDED_ON DATE ,
    PARAM_VAL VARCHAR2(50)
    );

CREATE SEQUENCE BST_ISE_SCH01.CONFIG_ID 
    START WITH 1 
    INCREMENT BY 1 
;
