SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS BST_ISE_SCH01;


CREATE TABLE ENTITL_AND_ACTN
  (
    COVG_BENI VARCHAR2(30 BYTE) NOT NULL ENABLE,
    COVG_VHCL   VARCHAR2(30 BYTE) NOT NULL ENABLE,
    DISPL_TXT   VARCHAR2(30 BYTE) NOT NULL ENABLE,
    ENTITL_DTL  VARCHAR2(500 BYTE),
    ACTNS       VARCHAR2(200 BYTE),
    CREATED_BY  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CREATED_ON DATE NOT NULL ENABLE,
    AMENDED_BY VARCHAR2(20 BYTE),
    AMENDED_ON DATE,
    CONSTRAINT ENTITL_AND_ACTN_PK1 PRIMARY KEY (COVG_BENI, COVG_VHCL) 
  );
  


CREATE TABLE RET_EXCH_DEVC_ENTITL
    (
      DTA_SHARING_KEY     VARCHAR2(100 BYTE) NOT NULL ENABLE,
      HANDSET_ID          VARCHAR2(50 BYTE) NOT NULL ENABLE,
      PH_NBR              VARCHAR2(30 BYTE) NOT NULL ENABLE,
      TRANS_KEY           VARCHAR2(30 BYTE),
      COVG_BENI           VARCHAR2(30 BYTE),
      COVG_BENI_PRMPT_CDE VARCHAR2(50 BYTE),
      COVG_VHCL           VARCHAR2(30 BYTE),
      TYPE                VARCHAR2(30 BYTE),
      PROTECTION_PLAN_ID  VARCHAR2(60 BYTE),
      DFEC_STAT           NUMBER(1,0),
      CREATED_BY          VARCHAR2(20 BYTE) NOT NULL ENABLE,
      CREATED_ON DATE NOT NULL ENABLE,
      AMENDED_BY VARCHAR2(20 BYTE),
      AMENDED_ON DATE,
      CONSTRAINT RET_EXCH_DEVC_ENTITL_PK PRIMARY KEY (DTA_SHARING_KEY) 
    );


