SET MODE Oracle;

CREATE TABLE "BST_ISE_SCH01"."AVG_STOR_TRFC"
(
   AVG_STOR_TRFC_ID decimal(12) PRIMARY KEY NOT NULL,
   STOR_TYP_ID decimal(12) NOT NULL,
   WKDY decimal(1) NOT NULL,
   HH_END decimal(2) NOT NULL,
   CUML_TRFC_PCT decimal(5,4) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_DLY_EMP"
(
   NTL_MRGN_DLY_EMP_ID decimal(12) PRIMARY KEY NOT NULL,
   NTL_MRGN_EMP_ID decimal(12) NOT NULL,
   STOR_ID varchar2(10) NOT NULL,
   BSNS_SRC_ID decimal(12) NOT NULL,
   SHIFT_BEG_TM timestamp,
   SHIFT_END_TM timestamp,
   PRIMARY_ZONE_ID decimal(12),
   SECONDARY_ZONE_ID decimal(12)
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_DLY_WGT"
(
   NTL_MRGN_DLY_WGT_ID decimal(12) PRIMARY KEY NOT NULL,
   BSNS_SRC_ID decimal(12) NOT NULL,
   WGT_DT timestamp NOT NULL,
   WGT_CAT_ID decimal(12) NOT NULL,
   WGT_VAL decimal(5,4) NOT NULL,
   WGT_WK decimal(1) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_EMP"
(
   NTL_MRGN_EMP_ID decimal(12) PRIMARY KEY NOT NULL,
   BBY_EMP_ID varchar2(100) NOT NULL,
   EMP_NM varchar2(80)
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_MTHLY_TGT"
(
   NTL_MRGN_MTHLY_TGT_ID decimal(12) PRIMARY KEY NOT NULL,
   BSNS_SRC_ID decimal(12) NOT NULL,
   STOR_ID varchar2(10) NOT NULL,
   NTL_MRGN_TGT_ID decimal(12) NOT NULL,
   NTL_MRGN_TGT_VAL decimal(30,15) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_STOR_GOAL"
(
   NTL_MRGN_STOR_GOAL_ID decimal(12) PRIMARY KEY NOT NULL,
   STOR_ID varchar2(10) NOT NULL,
   BSNS_SRC_ID decimal(12) NOT NULL,
   GOAL_TYP_ID decimal(12) NOT NULL,
   GOAL_VAL decimal(8,2) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_STOR_WGT"
(
   NTL_MRGN_STOR_WGT_ID decimal(12) PRIMARY KEY NOT NULL,
   BSNS_SRC_ID decimal(12) NOT NULL,
   STOR_ID varchar2(10) NOT NULL,
   WGT_CAT_ID decimal(12) NOT NULL,
   WGT_VAL decimal(5,4) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_TRANS"
(
   NTL_MRGN_TRANS_ID decimal(12) PRIMARY KEY NOT NULL,
   TRAN_TYP_ID decimal(12) NOT NULL,
   STOR_ID varchar2(10) NOT NULL,
   NTL_MRGN_DLY_EMP_ID decimal(12),
   NTL_MRGN_VAL_ID decimal(12) NOT NULL,
   QTY decimal(4) NOT NULL,
   AMT decimal(7,2),
   TRAN_DT timestamp NOT NULL,
   DEL_FLG decimal(1,0) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE TABLE "BST_ISE_SCH01"."NTL_MRGN_VAL"
(
   NTL_MRGN_VAL_ID decimal(12) PRIMARY KEY NOT NULL,
   BSNS_SRC_ID decimal(12) NOT NULL,
   NTL_MRGN_ITEM_ID decimal(12) NOT NULL,
   NTL_MRGN_ITEM_VAL decimal(7,2) NOT NULL
   , CREATED_BY VARCHAR2(40 ) NOT NULL 
, CREATED_ON DATE NOT NULL 
, AMENDED_BY VARCHAR2(40 ) 
, AMENDED_ON DATE
)
;
CREATE UNIQUE INDEX AVG_STOR_TRFC_UK1 ON "BST_ISE_SCH01"."AVG_STOR_TRFC"
(
  STOR_TYP_ID,
  WKDY,
  HH_END
)
;
CREATE UNIQUE INDEX AVG_STOR_TRFC_PK ON "BST_ISE_SCH01"."AVG_STOR_TRFC"(AVG_STOR_TRFC_ID)
;
ALTER TABLE "BST_ISE_SCH01"."NTL_MRGN_DLY_EMP"
ADD CONSTRAINT NTL_MRGN_DLY_EMP_FK1
FOREIGN KEY (NTL_MRGN_EMP_ID)
REFERENCES "BST_ISE_SCH01"."NTL_MRGN_EMP"(NTL_MRGN_EMP_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_DLY_EMP_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_DLY_EMP"
(
  NTL_MRGN_EMP_ID,
  STOR_ID,
  BSNS_SRC_ID
)
;
CREATE UNIQUE INDEX NTL_MRGN_DLY_EMP_PK ON "BST_ISE_SCH01"."NTL_MRGN_DLY_EMP"(NTL_MRGN_DLY_EMP_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_DLY_WGT_PK ON "BST_ISE_SCH01"."NTL_MRGN_DLY_WGT"(NTL_MRGN_DLY_WGT_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_DLY_WGT_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_DLY_WGT"
(
  BSNS_SRC_ID,
  WGT_DT,
  WGT_CAT_ID
)
;
CREATE UNIQUE INDEX NTL_MRGN_EMP_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_EMP"(BBY_EMP_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_EMP_PK ON "BST_ISE_SCH01"."NTL_MRGN_EMP"(NTL_MRGN_EMP_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_MTHLY_TGT_PK ON "BST_ISE_SCH01"."NTL_MRGN_MTHLY_TGT"(NTL_MRGN_MTHLY_TGT_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_MTHLY_TGT_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_MTHLY_TGT"
(
  BSNS_SRC_ID,
  STOR_ID,
  NTL_MRGN_TGT_ID
)
;
CREATE UNIQUE INDEX NTL_MRGN_STOR_GOAL_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_STOR_GOAL"
(
  STOR_ID,
  BSNS_SRC_ID,
  GOAL_TYP_ID
)
;
CREATE UNIQUE INDEX NTL_MRGN_STOR_GOAL_PK ON "BST_ISE_SCH01"."NTL_MRGN_STOR_GOAL"(NTL_MRGN_STOR_GOAL_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_STOR_WGT_PK ON "BST_ISE_SCH01"."NTL_MRGN_STOR_WGT"(NTL_MRGN_STOR_WGT_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_STOR_WGT_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_STOR_WGT"
(
  BSNS_SRC_ID,
  STOR_ID,
  WGT_CAT_ID
)
;
ALTER TABLE "BST_ISE_SCH01"."NTL_MRGN_TRANS"
ADD CONSTRAINT NTL_MRGN_TRANS_FK1
FOREIGN KEY (NTL_MRGN_DLY_EMP_ID)
REFERENCES "BST_ISE_SCH01"."NTL_MRGN_DLY_EMP"(NTL_MRGN_DLY_EMP_ID)
;
ALTER TABLE "BST_ISE_SCH01"."NTL_MRGN_TRANS"
ADD CONSTRAINT NTL_MRGN_TRANS_FK2
FOREIGN KEY (NTL_MRGN_VAL_ID)
REFERENCES "BST_ISE_SCH01"."NTL_MRGN_VAL"(NTL_MRGN_VAL_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_TRANS_PK ON "BST_ISE_SCH01"."NTL_MRGN_TRANS"(NTL_MRGN_TRANS_ID)
;
CREATE UNIQUE INDEX NTL_MRGN_VAL_UK1 ON "BST_ISE_SCH01"."NTL_MRGN_VAL"
(
  BSNS_SRC_ID,
  NTL_MRGN_ITEM_ID
)
;
CREATE UNIQUE INDEX NTL_MRGN_VAL_PK ON "BST_ISE_SCH01"."NTL_MRGN_VAL"(NTL_MRGN_VAL_ID)
;

CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_DLY_EMP_ID INCREMENT BY 1 START WITH 100; 
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_DLY_WGT_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_EMP_ID INCREMENT BY 1 START WITH 100;
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_VAL_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_TRANS_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_STOR_WGT_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_STOR_GOAL_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BST_ISE_SCH01.NTL_MRGN_MTHLY_TGT_ID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BST_ISE_SCH01.AVG_STOR_TRFC_ID INCREMENT BY 1 START WITH 1;
