DROP SEQUENCE BST_ISE_SCH01.TRIAGE_ACTN_SEQ;
DROP SEQUENCE BST_ISE_SCH01.TRIAGE_HIST_SEQ;
DROP SEQUENCE BST_ISE_SCH01.TRIAGE_ISSU_LKP_SEQ;
DROP SEQUENCE BST_ISE_SCH01.TRIAGE_RCMD_SEQ;
DROP SEQUENCE BST_ISE_SCH01.TRIAGE_RCMD_ACTN_SEQ;
DROP SEQUENCE BST_ISE_SCH01.TRIAGE_RSLN_LKP_SEQ;

DROP TABLE BST_ISE_SCH01.TRIAGE_HIST IF EXISTS;
DROP TABLE BST_ISE_SCH01.TRIAGE_RCMD_ACTN IF EXISTS;
DROP TABLE BST_ISE_SCH01.TRIAGE_RCMD_SKU IF EXISTS;
DROP TABLE BST_ISE_SCH01.TRIAGE_ACTN IF EXISTS;
DROP TABLE BST_ISE_SCH01.TRIAGE_ISSU_LKP IF EXISTS;
DROP TABLE BST_ISE_SCH01.TRIAGE_RCMD IF EXISTS;
DROP TABLE BST_ISE_SCH01.TRIAGE_RSLN_LKP IF EXISTS;
DROP TABLE BST_ISE_SCH01.SKU IF EXISTS;