


DROP SEQUENCE BST_ISE_SCH01.WORKFLOW_STEP_HIST_SEQ;

DROP SEQUENCE BST_ISE_SCH01.WORKFLOW_SEQ;

DROP SEQUENCE BST_ISE_SCH01.WORKFLOW_ATTRIBUTE_SEQ;

DROP SEQUENCE BST_ISE_SCH01.SEQ_RECOMMENDATION_ESSENTIAL;

DROP SEQUENCE BST_ISE_SCH01.SEQ_RECOMMENDATION_ESENTL_TYPE;

DROP SEQUENCE BST_ISE_SCH01.SEQ_RECOMMENDATION;

DROP SEQUENCE BST_ISE_SCH01.SEQ_CUSTOMER_DEVICE;

DROP SEQUENCE BST_ISE_SCH01.SEQ_CUSTOMER;

DROP SEQUENCE BST_ISE_SCH01.ISE_PROPERTIES_SEQ;

DROP SEQUENCE BST_ISE_SCH01.HOTLINKS_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DIALOG_QUESTION_HIST_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DIALOG_QUESTION_DIALOG_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DIALOG_QUESTION_ANSWER_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DIALOG_HISTORY_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DG_QUESTION_ANSWER_HIST_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DEVICE_SEQ;

DROP SEQUENCE BST_ISE_SCH01.DEVICE_GROUP_SEQ;


DROP TABLE WORKFLOW_ATTRIBUTE_HIST IF EXISTS;

DROP TABLE RECOMMENDATION_ESSENTIAL IF EXISTS;

DROP TABLE RECOMMENDATION_ESSENTIAL_TYPE IF EXISTS;

DROP TABLE RECOMMENDATION IF EXISTS;

DROP TABLE ISE_PROPERTIES IF EXISTS;

DROP TABLE HOTLINKS IF EXISTS;

DROP TABLE DIALOG_QUESTION_ANSWER_HIST IF EXISTS;

DROP TABLE DIALOG_QUESTION_HIST IF EXISTS;

DROP TABLE DIALOG_QUESTION_ANSWER IF EXISTS;

DROP TABLE DIALOG_QUESTION IF EXISTS;

DROP TABLE DIALOG_HISTORY IF EXISTS;

DROP TABLE WORKFLOW_STEP_HIST IF EXISTS;

DROP TABLE WORKFLOW IF EXISTS;

