
DROP SEQUENCE OS_LKUP_SEQ;

DROP SEQUENCE CARR_LKUP_SEQ;

DROP SEQUENCE bst_ise_sch01.PHONE_SEQ;

DROP TABLE BST_ISE_SCH01.PHONE_EXTRAS;

DROP SEQUENCE bst_ise_sch01.CHKOUT_CHKIN_HIST_SEQ;

DROP SEQUENCE bst_ise_sch01.PH_EXTRAS_SEQ;

DROP TABLE BST_ISE_SCH01.CHKOUT_CHKIN_HIST;

DROP TABLE BST_ISE_SCH01.LOANR_PH;

DROP TABLE BST_ISE_SCH01.OS_LKUP;

DROP TABLE BST_ISE_SCH01.CARR_LKUP;

DROP SCHEMA BST_ISE_SCH01;